- .gitignore
- reporters_db/data/reporters.csv
- reporters_db/data/reporters.json
- tests.py
Update to reporters-db
Added two variations on T.C. 
Added T.C. Memo
Added T.C. Summary Opinions
Added T.C. No.
> feat (reporters.json) Add additional Tax Reporters

- reporters_db/data/reporters.json
I'm assuming this was a typo, at least!
> Fix punctuation typo

- .github/workflows/lint.yml
- pyproject.toml
- reporters_db/__init__.py
- reporters_db/make_csv.py
- reporters_db/utils.py
- setup.py
- tests.py
This repo wasn't previously formatted with Black so I added the `pyproject.toml` and formatted it. There weren't altogether too many changes.
> Feature: use official Black action

- reporters_db/data/regexes.json
- reporters_db/utils.py
A couple quick tweaks that seemed useful once I tried integrating this with eyecite.
> Eyecite tweaks

- tests.py
Sending this separately to get tests passing on other PRs.
> Update formatting for black 21.4b0

- .pre-commit-config.yaml
- CHANGES.md
- reporters_db/__init__.py
- reporters_db/data/reporters.json
- reporters_db/make_csv.py
- reporters_db/utils.py
- setup.py
- tests.py
Updates for 
Ark
Ark App
Me
Tex. Crim.
Wash. Terr.
> Update Various Reporters

- reporters_db/data/reporters.json
Add 
ED SMITH
Gibb. Surr.
Hiltons
Howards Appeal
Liquor Tax Law Reports
Powers Surrogates 
Redfield Reports
Selden Notes
Silvernails and Silvernails Supreme
Transcript Appeals
Tuckers Surrogates
Wheelers Criminal Cases
> Add NY Reporters

- reporters_db/data/reporters.json
Update ny reporters from harvard import
> feat(ny): Update Reporters

- reporters_db/data/reporters.json
PR Adds parson Reporter
Also updates variation for serge and rawle
> Update Two PA reporters

- CHANGES.md
- reporters_db/data/reporters.json
PR Adds a handful of 17th century Massachusetts reporters
> feat(reporters): Update mass reporters

- reporters_db/data/reporters.json
Adds another round of reporters that were missing from reporters db.
> Add 75 new Reporters

- reporters_db/data/laws.json
- reporters_db/data/regexes.json
- reporters_db/data/reporters.json
Add more reporters and variations
Fix Federal Register to laws and remove from reporters
> Update more reporters

- reporters_db/data/reporters.json
Minor PR to fix an errant removal of a variation
> fix(nw2d): Add missing variation accidentally removed

- .github/workflows/eyecite.yml
This PR should add support for testing against eyecite.
> feat(workflow): Add eyecite check GitHub action

- reporters_db/data/reporters.json
Add additional reporters and Variations
> feat(reporters): Add various reporters

- reporters_db/data/reporters.json
New reporter: Howison's Criminal Trials
I need to validate if cite_type is correct.
This is where i got the information: https://www.legalabbrevs.cardiff.ac.uk/titles/tview/id/9298/tsearch//ttype/Exact
> New reporter: Howison

- reporters_db/data/reporters.json
> feat(reporters.json): update fapp'x variations

- reporters_db/data/reporters.json
Add California AG to reporters-db
> feat(cal-ag): Add California AG

- CHANGES.md
- reporters_db/data/reporters.json
- setup.py
Solves a comment in freelawproject/juriscraper#922
> feat(V.I.): add VI format to V.I.

- reporters_db/data/reporters.json
Add neutral citaitons for NH
add regex to state citation NH 
to allow for differentiation
> feat(reporters): Add Neutral Citation (NH)

- reporters_db/data/reporters.json
Small fix for Auto Cas CCH reporter
> fix(repoters): Add regex pattern for auto cas cch pattern

- reporters_db/data/reporters.json
Add variations - remove duplicate listing
> fix(repoters): Update federal appendix

- reporters_db/data/reporters.json
> feat(add-ny-abbreviation): Missing ny variation

- reporters_db/data/reporters.json
Small addition to NY variations
> Update ad3d variations

- CHANGES.md
- reporters_db/data/reporters.json
NY Variations - with square brackets and whitespaces unique to NY
> More ny square brackets whitespace variations

- reporters_db/data/reporters.json
> feat(sct): Update regex SCT

- CHANGES.md
- setup.py
> version bump v3.2.54

- .github/workflows/lint.yml
- .github/workflows/tests.yml
A copy of https://github.com/freelawproject/courts-db/pull/108 for this repository.
> fix(ci): Separate concurrency groups by workflow

- CHANGES.md
- pyproject.toml
- uv.lock
> version bump v3.2.57
