freelawproject/reporters-db

reporters.json
* ID schema has changed, but is now stable, with:
- jurisdiction element delimited with a colon; and
- court appended to jurisdiction with a semicolon
* The only changes to reporters.json with this checkin are
in the mlz_jurisdiction identifiers.
* The PR restores the following entries to the B.R. reporter
(both are present in a report of CL data, but had gone
missing when the previous reporters.json was generated)
- txwb / us:c5:tx.wd;bankruptcy.court
- wvnb / us:c4:wv.nd;bankruptcy.court
* The PR restores the following entries to the U.S. Dist. LEXIS
reporter (again, both are present in a report of CL data, but had
gone missing when the previous version of reporters.json was
generated)
- southcarolinaed / us:c4:sc.ed;district.court
- southcarolinawd / us:c4:sc.wd;district.court
=> Update IDs from upstream LRR

reporters_db/data/reporters.json
Here's a first pass at incorporating reporter aliases that we discovered when searching CAP data for [digit] [text] [digit] patterns. 
There are links to cases using each of these cite formats in the Google spreadsheet I sent. Here's a copy for posterity: [missed_citations.csv.zip](https://github.com/freelawproject/reporters-db/files/4439833/missed_citations.csv.zip). The IDs in that file can be turned into cases by appending them to "https://api.case.law/v1/cases/" and then clicking frontend_url.
This PR includes changes from manually confirmed entries appearing 10,000 or more times in our corpus but not in reporters-db. I don't know if all of this should be accepted. Some specific notes and questions:
* It is fairly common to have an existing cite form followed by "Rep.", like "Atl. …
=> Variations detected by analyzing CAP caselaw data

reporters_db/data/reporters.json
Just ran into a random test failure that turned out to be because of this stray space in the json file ...
=> Remove extra space

reporters_db/data/reporters.json
This adds `cite_format`, `examples`, and `regexes` for the NMSC, NMCA, NMCERT, and Ohio neutral citation formats, which are all in the format `year-reporter-id`.
Questions:
* There's an `"NM"` neutral cite format in reporters.json. Is that a real format? I don't see it [documented by LII](https://www.law.cornell.edu/citation/3-200#3-210_New_Mexico) for example.
* Ohio lists the official edition as "OH" with a variation for "Ohio." Is that correct? [LII shows](https://www.law.cornell.edu/citation/3-200#3-210_Ohio) the correct format as "Ohio" rather than "OH".
=> Add details for NM and Ohio neutral citation formats

reporters_db/data/reporters.json
This PR adds a bunch of variations with an existing reporter string plus "Rep." The process was to look at CAP's [spreadsheet](https://docs.google.com/spreadsheets/d/1TsxGPpzGKKFLq8isLr_l9Zr_HfwyRsOram2sN7GPjz8/edit#gid=0) of cite-like strings, and find all strings where the reporter name would be valid if "Rep." was removed.
(A side effect of injecting these new values was to alphabetize all of the `"variations"` dicts, so there are a few instances in the diff where the dict is alphabetized but otherwise unchanged. I kept that behavior because keeping the dicts alphabetized seemed like a good idea anyway, to reduce future typos. Alphabetization could be added to the tests potentially.)
reporters-db already had the high-frequency "Rep." variations, so this covers the lower-frequency ones. …
=> Add variations with "Rep." at the end

reporters_db/data/reporters.json, tests.py
Per the suggestion in #29, here's a json formatting check as a test. The one little oddity is you can call it as `FIX_JSON=1 python tests.py` to get formatting automatically applied. That's clunky but less clunky than having to read the diff and apply alphabetizing by hand.
=> Add test to check json is sorted and otherwise normally formatted

reporters_db/data/reporters.json
This update covers a reporter I was unaware of, the [Reports of cases argued and determined in the Superior Court of the city of New York](https://catalog.hathitrust.org/Record/008606745).
That's the official reporter for seven nominatives. From the link:
"Reporters: v. 1-2, Jonathon Prescott Hall; v. 3-7, Lewis H. Sandford; v. 8-13, John Duer; v. 14-23, Joseph S. Bosworth; v. 24-30, Anthony L. Robertson; v. 31-32, James M. Sweeny; v. 33-61, Samuel Jones and James C. Spencer."
I verified the short cites as well as I could by pulling out N.Y. Super. Ct. cites from our collection and checking parallel cites, so I think the short cites I included here are pretty much right. There's nothing official about the `"name"` fields I chose; I just conformed everything to the existing name field for …
=> Update reporters for N.Y. Super. Ct.

reporters_db/data/reporters.json
Following up on the questions in #26, this fixes a few things:
* The neutral cite format for NM appears to be only "NMCA", "NMSC", etc., not "NM". Remove "NM".
* The neutral cite format for Ohio appears to only be "Ohio", not "OH". Fixing this involves moving the Ohio definition to a different top-level key, which I hope I did correctly.
* The Watts & Serg. variation "W. & S." is missing a space.
I checked that these three changes are consistent with CAP data -- we didn't extract any cites before that would be lost by these changes. If the formats are used elsewhere of course I'm fine with leaving them in.
Ongoing questions:
* I'm not sure why "NM" and "OH" were there in the first place -- is it possible there's some other source that does use those formats? I only checked citation …
=> Remove extra neutral citation formats

reporters_db/data/reporters.json
This was removed in #34 when I moved the Ohio reporter (under the "Remove variations on Ohio neutral citation format; move to 'Ohio' key" commit), but the change was lost somehow in the merge.
=> Remove duplicate OH reporter

reporters_db/data/reporters.json
Some reporters I found while cleaning up CAP metadata.
Smith ([CAP page](https://cite.case.law/smith-n-h/)) is a little atypical because it's one volume, and cites to it seem to always include the "(N. H.)" and exclude the volume number, so they look like `Twombly v. Baker, Smith (N. H.) 123`.
I know we usually would put "Smith" as the main edition name and "Smith (N. H.)" as the variation, but that feels like adding unnecessary disambiguation work if this volume is never actually cited as "Smith."
As far as cites typically dropping the volume number, I tried adding `"cite_format": "{reporter} {page}"`. Dunno if this will cause problems downstream, but otherwise you don't find the cites ...
=> Add Bland, Md. Ch., Ct. Cl. (W.V.), and Smith (N.H.)

reporters_db/data/reporters.json, tests.py
This is a first pass at updating reporters-db based on matches with CAP's list of reporters (issue #8).
I [ran a report](https://docs.google.com/spreadsheets/d/1-BIxF3p_ThG1WO_p6PINpDkgFdB9iGz615lzPjTd-uQ/edit#gid=0) of all CAP reporters whose short names didn't appear in reporters-db.
About half the time this is because of a mistake in CAP, and half the time it's because of a missing entry in reporters-db. Sometimes it's because of both. Each takes some detective work to resolve, so I only did the ones where there were more than 1,000 or so cases in CAP's collection for that reporter.
=> Update reporters by comparing to CAP reporter list

README.rst, reporters_db/__init__.py, reporters_db/data/regexes.json, reporters_db/data/reporters.json, reporters_db/data/variables.json, reporters_db/utils.py, tests.py
Following up on the discussion [over here](https://github.com/freelawproject/eyecite/pull/31), this adds a proposed new field under each edition called `"patterns"` that specifies regexes mapping to that edition. I'm filing this now for comment before getting too far into implementation.
To simplify the regexes, this follows the example of courts-db by expanding placeholders from variables.json, but with the addition of recursive resolution and some additional special-case expansion for "$edition". Here's the intended expansion of the first entry, for example:
```
"Bankr. L. Rep.": [
{
"editions": {
"Bankr. L. Rep.": {
"patterns": [
"$paragraph_cite"
],
}
},
"variations": {
"Bankr. L. Rep. (CCH)": "Bankr. L. Rep."
}
}
```
Expansion steps:
* Recursive expansion from variables.json:
* …
=> Add new patterns field

reporters_db/data/reporters.json
Quick fix -- "Abb. Pr. (n.s.)" is a separate reporter series:
http://cite.case.law/abb-pr
http://cite.case.law/abb-pr-ns
=> Separate edition for Abb. Pr. (n.s.)

reporters_db/data/reporters.json
This adds regexes for the non-numeric volume numbers in CAP's collection --
* 17A N.Y. 2d
* 25 Tex. Supp. (volume 25 Supp. of the Texas reports)
* 81 1/2 Pa.
* 33 Ga. Supp. (volume 33 Supp. of the Georgia reports)
* 402A Mich.
I think it's correct to collapse the separate "Ga. Supp." and "Tex. Supp." reports into these, but I dunno, these are all pretty weird.
=> Handle non-numeric volume numbers

reporters_db/data/regexes.json, reporters_db/data/reporters.json
Add a custom regex for Illinois format-neutral cites like `2014 IL App (3d) 120583-U`, so we can drop the generic `r"\d{1,6}[-]?[a-zA-Z]{1,6}",  # CT/IL page` regex from eyecite.
I can't find any evidence of a CT cite format like this, so didn't add it here -- will follow up over in the eyecite repo.
=> Add Illinois format-neutral regexes

reporters_db/data/reporters.json
I'm not sure if this cite format is cited to, but here's a CourtListener case that lists it as a citation:
Knise v. Knise, No. Fa98 0165989 S (Oct. 4, 1999), 1999 Conn. Super. Ct. 13301-M (Conn. Super. Ct. 1999)
https://www.courtlistener.com/opinion/3347363/knise-v-knise-no-fa98-0165989-s-oct-4-1999/
=> Add Conn. Super. Ct. format-neutral cite

reporters_db/data/reporters.json
Oops looks like "1993 Ct. Sup. 3588" at least is a real case, so I should have copied the variations over from the other Conn. Super. Ct. reporter.
=> Apply Conn. Super. Ct. variations to both reporters

reporters_db/data/regexes.json, reporters_db/data/reporters.json, tests.py
I'm taking a first pass at extracting citation patterns from the Indigo Book.
I started by just checking what state-court citation patterns are included in Indigo Book but not matched by eyecite. That resulted in this PR.
The biggest reason eyecite failed to match was that we weren't matching internal parallel cites to nominative reporters. Indigo Book specifies that we should match cites like "18 Mass. (1 Pick.) 123", which means "18 Mass. 123, formerly known as 1 Pick. 123". I added regex patterns so those will come in as `volume: "18", reporter: "Mass.", page: "123", volume_nominative: "1", reporter_nominative: "Pick."`. Eyecite can do something with those extra regex match groups later or just ignore them, which I think would be fine.
Other than that it was just fixing a bunch of …
=> Add missing case reporters from Indigo Book

reporters_db/__init__.py, reporters_db/data/journals.json, reporters_db/data/laws.json, reporters_db/data/regexes.json, reporters_db/data/reporters.json, tests.py
This is a first pass at importing the spreadsheet from #13 to a new journals.json file.
Proposed format:
```
"A.B.A. J.": [
{
"cite_type": "journal",
"end": null,
"name": "ABA Journal",
"notes": "Automatically generated 2021-05-04.",
"start": null,
"variations": {}
}
],
```
Notes and open questions:
* They all have `"cite_type": "journal"`, I guess in case that gets more precise later? Could remove this.
* I didn't keep `"editions"` from reporters.json, but I did keep each entry as a list so there could hypothetically be more than one under a given key like `"A.B.A. J."`. This could be tweaked in either direction.
* I imagine we would add `"regexes"` if and when we find non-standard citation forms for some of these.
* Some of the spreadsheet entries already existed in reporters.json. Any …
=> Ingest journals spreadsheet

reporters_db/__init__.py, reporters_db/data/laws.json, reporters_db/data/regexes.json, reporters_db/data/reporters.json, tests.py
Here's a first pass at adding `laws.json` based on the state-by-state rules from the [Indigo Book](https://law.resource.org/pub/us/code/blue/IndigoBook.html#T3). Offering for discussion!
See below for the full file, but this initial proposal is basically a few hundred entries that look like this:
```
{
"cite_type": "leg_statute",
"end": null,
"examples": [
"Ala. Code § 92.979 (1999)"
],
"jurisdiction": "Alabama",
"name": "Code of Alabama, 1975 (West)",
"notes": "Automatically generated on 2021-04-30. Remove this message if replacing with real examples.",
"regexes": [
"Ala\\. Code § $statute_section \\($statute_year\\)"
],
"start": null
}
```
Open questions:
* Do we like putting all the non-court legislative and executive stuff in "laws.json"?
* Top level structure: this is a list of …
=> Add laws.json

reporters_db/data/laws.json, tests.py
This covers everything in Indigo Book T1 "[Federal Judicial and Legislative Materials](https://law.resource.org/pub/us/code/blue/IndigoBook.html#T1)" -- I verified that the rest was already covered in reporters.json.
I'll file an issue for T2, the administrative materials, and anything else that looks interesting.
=> Add U.S.C. to laws.json

reporters_db/data/laws.json, reporters_db/data/regexes.json, reporters_db/data/reporters.json, tests.py
This continues work on #48 by adding the "[Federal Administrative and Executive Materials](https://law.resource.org/pub/us/code/blue/IndigoBook.html#T2)" section from the Indigo Book.
As mentioned in #48, this is rife with judgment calls, so I just tried to grind through and get it 90% done. From here we can look for what's missed in cases.
Also in this PR: 
* Tests don't run if they're prefixed "text_" apparently.
* I threw in patents and trademarks because I'm curious what comes out! Trademarks just look like "Registration No. 3,886,986" and might turn out to be overinclusive.
=> Federal Administrative and Executive Materials

reporters_db/data/journals.json
When I moved these entries over from reporters.json to journals.json, I failed to update their `variations` from dicts to lists. Variations in journals are expected to be lists because there's no editions to disambiguate.
Separate PR before too long to validate reporters-db json with jsonschema to avoid this kind of mistake.
=> Update journals.json variations that should be lists

schemas/journals.json, schemas/laws.json, schemas/regexes.json, schemas/reporters.json, setup.py, tests.py
This adds schemas for each json file in the `schemas/` dir, and checks that they validate with the [jsonschema](https://pypi.org/project/jsonschema/) library.
So for example if I add a misspelling of "examples" as "exmaples", I get this test failure:
```
E           jsonschema.exceptions.ValidationError: 'examples' is a required property
E
...
E
E           On instance['ASBCA'][0]:
E               {'cite_type': 'admin_docket',
E                'end': None,
E                'exmaples': ['ASBCA No. 43466'],
E                'href': 'https://law.resource.org/pub/us/code/blue/IndigoBook.html#T2',
E                'jurisdiction': 'United States',
E                'name': 'Armed Services Board of Contract Appeals',
E                'regexes': ['$reporter No. (?P<docket_number>\\d+)'],
E …
```
=> Test json files with jsonschema

reporters_db/__init__.py
`with open(os.path.join(db_root, "data", "laws.json")) as f:` -> 
`with open(os.path.join(db_root, "data", "laws.json"), encoding="utf-8") as f:`
Fixes #72. 
Windows users may have a locale encoder that is not utf-8, and because Python's [`open()`](https://docs.python.org/3/library/functions.html#open) uses the locale encoder, this variance can corrupt symbols (such as § in laws.json) for those Windows users.
Added `encoding="utf-8"` when opening laws.json to solve the locale encoder issue for that file.
If other files with symbols like § were to be opened without encoding="utf-8", they could have the same issue. For now, I only noticed this to affect laws.json so I added it there.
Also, this is my first PR so please give feedback and advice on what to do differently!
=> Fixed #72: ensured utf-8 when opening laws.json

CHANGES.md, reporters_db/data/reporters.json
The full cite is too broad and allows for
incorrect matching.  Limit to three digit volume
Fix typo in changelog
=> feat(ark): Update Arkansas state regex pattern

reporters_db/data/reporters.json
This pull request is a test pull request as discussed in [this issue](https://github.com/freelawproject/eyecite/issues/103) on the eyecite repository. This PR makes two changes adding some historical information:
- Kelly is added as an antique (nominative) reporter for the first five volumes of the Georgia Reports.
- The abbreviation `Oreg.`, frequently used in historical legal documents, is added for Oregon.
Tests in the reporters-db repository pass locally after these changes. Informal tests of whether eyecite can pick up citations in these formats also work. Please let me know if there is a more explicit kind of test that needs to be added when making additions like this.
=> Add historical citation formats from Georgia and Oregon

reporters_db/__init__.py
If you work on Windows like me you will probably run into the same problem as me. I'm working with files with Unicode characters, when you use the python open() function to open a file without specifying explicitly the encoding it will be platform dependent, in the case of Windows the function will return cp1252 encoding instead of utf-8.  You can read more about it right here: https://docs.python.org/3/library/functions.html#open
This change specifies encoding to utf-8 to ensure cross-platform compatibility when opening files in text mode. In this case when loading the json files for reporters, state abbreviations, case name abbreviations, etc.
=> Specify encoding to ensure cross-platform support when opening file

reporters_db/data/laws.json
Addresses #116 by adding support for public law citations. Also has support for private law citations, though these are sufficiently rare that it may not be worth keeping this reporter.
=> Add support for U.S. Public and Private Laws

CHANGES.md, reporters_db/data/reporters.json
After being working with incorrect citations from CL logs, I was able to identify some missing reporters. These are the new reporters that I added to the reporters' db.
It would be a great help if you could help me to validate that the cite type is correct.
=> New reporters added

reporters_db/data/reporters.json
Too many false positives.  Detected now.
This also questions why now?
=> feat(reporters): Drop Page as variation for pacific

reporters_db/data/reporters.json
New reporters variations found in courtlistener logs, some of them include unicode characters but others are very interesing because the  the reporter short name changed drastically, I am attaching a csv with the IA url, case.law url, the old citation and the new citation with some of this short name changes.
[reporters_changes.csv](https://github.com/freelawproject/reporters-db/files/9539309/reporters_changes.csv)
=> Add various Reporters variations

reporters_db/data/reporters.json
A regex pattern was added that matched to a pin
cite and thus not a complete page cite.
Dropped it.
Also ... the S. reporter variation is causing
down stream problems  I dont fully grasp.
Removing it for now.
=> fix(reporters): Two minor tweaks

reporters_db/data/regexes.json, reporters_db/data/reporters.json
This changes includes:
- New reporters variations found in courtlistener logs.
- New regex pattern for a page number followed by a letter, e.g. 246 Ga. 822a or 44 App. D.C. 154b
- Updated regex pattern: $full_cite_year_included to include optional comma after year, e.g. 3 N. B. R. (1870,) 575
- New reporter N.B.R. (Supp.) (https://law.resource.org/pub/us/case/reporter/F.Cas/0001.f.cas/0001.f.cas.front.html)
- New reporter: American Railway Reports (https://www.legalabbrevs.cardiff.ac.uk/titles/tview/id/283/tsearch//ttype/Exact)
- Alabama reports variation: alabama reports new series (https://www.legalabbrevs.cardiff.ac.uk/titles/tview/id/497/tsearch//ttype/Exact)
=> New reporters, new reporters variations and new regex pattern

reporters_db/data/reporters.json
- New reporter Syllabi
- New reporter Oliver's Forms
- New reporter Coddington's Digest of the Law of Trade-Marks
- New reporter Cox's Manual of Trade-Mark Cases
- New reporter Wharton's State Trials
- New reporter Wharton, Treatise on the Law of Homicide in the United States
- New reporter Maryland Law Record
- New reporter Robb's Patent Cases
- New reporter Cranch's Patent Decisions
- New reporter United States Law Journal and Civilians' Magazine
- New reporter Quarterly Law Journal
- New reporter San Francisco Law Journal
- New reporter Louisiana Law Journal
- New reporter Law and Equity Reporter
- New reporter Monthly Western Jurist
- New reporter Indian Claims Commission
- New reporter Law reporter
- New reporter Betts' Scrap Book
- New reporter American Law Journal, New Series
- New …
=> New reporters and reporter variations

reporters_db/data/reporters.json
Fix Mismatch for Ohio reporter between neutral and state citations.  
Regex pattern needed to be updated on both editions to 
correctly identify between neutral and state
=> feat(reporters): Update Ohio regex patterns

reporters_db/data/reporters.json
Update Neutral citations to include the Regex pattern.
Update the regex for Me. to not overlap with the neutral citations.
=> feat(reporters): Update maine neutral citations

reporters_db/data/reporters.json
Update to NY Slip Op and Misc3d
We get trailing letters U and A in
parentheses that need to be accounted for
in scraping
cc @grossir
=> feat(reporters): Update NY Reporters

reporters_db/data/reporters.json
This is meant to add a few variations for
failing parsing during the major citation
import
Adds some Florida Law Reporter Variations
Variations in Ohio and NM with whitespace
and some example variations
=> feat(reporters): Add a few more reporter variations

.github/workflows/lint.yml, reporters_db/data/reporters.json
New reporters variations added and new reporters added:
- Cal. WCC 
- CJ C.A.R.
- DJCAR
- Conn. Surr.
- FCDR
- Abbotts
Update: I had to update the lint workflow to force a specific version of black because the latest version does not support python 3.8. The latest supported version is 22.8.0
=> New reporters and reporters variations

reporters_db/data/reporters.json
Solves https://github.com/freelawproject/reporters-db/issues/186
=> feat(reporters): add PA Super neutral citation

reporters_db/data/regexes.json, reporters_db/data/reporters.json
Reporters updated: 
- A.F.T.R. (RIA) (Eyecite issue [#24](https://github.com/freelawproject/eyecite/issues/24))
- Fulton County D. Rep. (Eyecite issue [#23](https://github.com/freelawproject/eyecite/issues/23))
- Gilmer (Eyecite issue [#20](https://github.com/freelawproject/eyecite/issues/20))
- McCahon (Eyecite issue 20)
- Litt. Sel. Cas. (Eyecite issue 20)
`full_cite_single_volume` regex updated to allow optional comma
=> Update reporters and regexes

reporters_db/data/reporters.json
NY prefers to not use whitespace and periods 
THIS PR adds variations from their manual
=> Update NY state variations 

CHANGES.md, reporters_db/data/reporters.json
- Add variation to Montana Neutral Citation for citations like: `2021 MT 172A`
- Also added a note to know the meaning if the page number has a N or an A
=> Add variation to Montana Neutral Citation

CHANGES.md, reporters_db/data/regexes.json, reporters_db/data/reporters.json
- Updated "Chase" regex
- The capturing group for volume for nominative reporters changed from volume_nominative to volume to standardize it.
For example:
"1 Hask. 405"
`FullCaseCitation('1 Hask. 495',groups={'volume': '1', 'reporter': 'Hask.', 'page': '405'}....`
"Hask. 236"
`FullCaseCitation('Hask. 236', groups={'volume': None, 'reporter': 'Hask.', 'page': '236'}.....`
volume_nominative capturing group still exists for a few special cases when we have a parallel citation,it includes both official and nominative reporter citation, for example:
"20 N.C. (3 & 4 Dev. & Bat.) 456"
`FullCaseCitation('20 N.C. (3 & 4 Dev. & Bat.) 456', groups={'volume': '20', 'reporter': 'N.C.', 'volume_nominative': '3 & 4', 'reporter_nominative': 'Dev. & Bat.', 'page': '456'}...`
"21 D.C. (Tuck. & Cl.) 456" …
=> Standardize nominative reporters regex group name

.github/dependabot.yml, .github/workflows/lint.yml, .pre-commit-config.yaml, pyproject.toml, reporters_db/make_csv.py, reporters_db/utils.py, tests.py
Replace Black, isort, and pyupgrade with Ruff.
=> chore: Move formatting and linting to Ruff

README.rst
=> fix(docs): Unquote variable lists

CHANGES.md, reporters_db/data/laws.json, reporters_db/data/regexes.json
Tighten up standard volume regex to not use leading zeroes
000 Harper 123 and 00 Harper 123
were both being identified in a junk table
but then resolving to the same citation
and throwing a bug.  I can think of
zero known citations that start with 0
=> fix(regexes): Remove leading zero from volume

CHANGES.md, reporters_db/data/reporters.json
This pull request introduces changes to support the Texas Business Court Reporter.
this PR addresses -- #231
=> feat: Add Texas Business neutral citation to reporters.json
